import Car from "../assets/images/Car.png";
const Data = [
  {
    name: "Koenigsegg",
    image: Car,
    gasCapacity: "90L",
    transmission: "Manual",
    peopleCapacity: 2,
    rentalPerDay: "$99.00",
    status: "Popular",
  },
  {
    name: "Koenigsegg",
    image: Car,
    gasCapacity: "90L",
    transmission: "Manual",
    peopleCapacity: 2,
    rentalPerDay: "$99.00",
    status: "Popular",
  },
  {
    name: "Koenigsegg",
    image: Car,
    gasCapacity: "90L",
    transmission: "Manual",
    peopleCapacity: 2,
    rentalPerDay: "$99.00",
    status: "Popular",
  },

  {
    name: "Koenigsegg",
    image: Car,
    gasCapacity: "90L",
    transmission: "Manual",
    peopleCapacity: 2,
    rentalPerDay: "$99.00",
    status: "Popular",
  },
  {
    name: "Koenigsegg",
    image: Car,
    gasCapacity: "90L",
    transmission: "Manual",
    peopleCapacity: 2,
    rentalPerDay: "$99.00",
    status: "Popular",
  },
  {
    name: "Koenigsegg",
    image: Car,
    gasCapacity: "90L",
    transmission: "Manual",
    peopleCapacity: 2,
    rentalPerDay: "$99.00",
    status: "Recommendation",
  },
  {
    name: "Koenigsegg",
    image: Car,
    gasCapacity: "90L",
    transmission: "Manual",
    peopleCapacity: 2,
    rentalPerDay: "$99.00",
    status: "Recommendation",
  },
  {
    name: "Koenigsegg",
    image: Car,
    gasCapacity: "90L",
    transmission: "Manual",
    peopleCapacity: 2,
    rentalPerDay: "$99.00",
    status: "Recommendation",
  },
  {
    name: "Koenigsegg",
    image: Car,
    gasCapacity: "90L",
    transmission: "Manual",
    peopleCapacity: 2,
    rentalPerDay: "$99.00",
    status: "Recommendation",
  },
  {
    name: "Koenigsegg",
    image: Car,
    gasCapacity: "90L",
    transmission: "Manual",
    peopleCapacity: 2,
    rentalPerDay: "$99.00",
    status: "Recommendation",
  },
  {
    name: "Koenigsegg",
    image: Car,
    gasCapacity: "90L",
    transmission: "Manual",
    peopleCapacity: 2,
    rentalPerDay: "$99.00",
    status: "Recommendation",
  },
  {
    name: "Koenigsegg",
    image: Car,
    gasCapacity: "90L",
    transmission: "Manual",
    peopleCapacity: 2,
    rentalPerDay: "$99.00",
    status: "Recommendation",
  },
  {
    name: "Koenigsegg",
    image: Car,
    gasCapacity: "90L",
    transmission: "Manual",
    peopleCapacity: 2,
    rentalPerDay: "$99.00",
    status: "Recommendation",
  },
  {
    name: "Koenigsegg",
    image: Car,
    gasCapacity: "90L",
    transmission: "Manual",
    peopleCapacity: 2,
    rentalPerDay: "$99.00",
    status: "Recommendation",
  },
  {
    name: "Koenigsegg",
    image: Car,
    gasCapacity: "90L",
    transmission: "Manual",
    peopleCapacity: 2,
    rentalPerDay: "$99.00",
    status: "Recommendation",
  },
];

export default Data;
